jjb: fix yamllint issues
Linting ci-AGL-verify and ci-management files

Change-Id: I81f50f82e0a43e09d4ec8c8d108b0f6ea1f19527
Signed-off-by: Jessica Wagantall <jwagantall@linuxfoundation.org>

diff --git a/jjb/ci-AGL-verify/ci-platform-jjb.yaml b/jjb/ci-AGL-verify/ci-platform-jjb.yaml
--- a/jjb/ci-AGL-verify/ci-platform-jjb.yaml
+++ b/jjb/ci-AGL-verify/ci-platform-jjb.yaml
@@ -1,31 +1,32 @@
+---
 - project:
     name: ci-platform-AGL
     machine:
-        - porter-nogfx
-        - raspberrypi3
-        - intel-corei7-64
-        - dra7xx-evm
-        - qemux86-64
+      - porter-nogfx
+      - raspberrypi3
+      - intel-corei7-64
+      - dra7xx-evm
+      - qemux86-64
     project:
-        - meta-agl
-        - meta-agl-demo
-        - meta-agl-devel
-        - meta-agl-extra
-        - AGL-repo
-        - meta-renesas
+      - meta-agl
+      - meta-agl-demo
+      - meta-agl-devel
+      - meta-agl-extra
+      - AGL-repo
+      - meta-renesas
     jobs:
-        - ci-platform-{project}-verify
-#        - ci-platform-{project}-verify-CIB-start
-        - ci-platform-{project}-verify-CIB-{machine}
-        - ci-platform-{project}-verify-CIB-finish-success
-        - ci-platform-{project}-verify-failure
-#        - ci-platform-{project}-verify-CIBT-start
-        - ci-platform-{project}-verify-CIBT-{machine}
-        - ci-platform-{project}-verify-CIBT-finish-success
+      - ci-platform-{project}-verify
+      # - ci-platform-{project}-verify-CIB-start
+      - ci-platform-{project}-verify-CIB-{machine}
+      - ci-platform-{project}-verify-CIB-finish-success
+      - ci-platform-{project}-verify-failure
+      # - ci-platform-{project}-verify-CIBT-start
+      - ci-platform-{project}-verify-CIBT-{machine}
+      - ci-platform-{project}-verify-CIBT-finish-success
 
 #
 # -verify  = trigger from gerrit and control job
-################################################
+# ###############################################
 
 - job-template:
     name: 'ci-platform-{project}-verify'
@@ -61,8 +62,8 @@
 
     triggers:
       - gerrit-trigger-patch-submitted-manual-verified:
-            name: 'AGL/{project}'
-            branch: '**/**/**'
+          name: 'AGL/{project}'
+          branch: '**/**/**'
 
     wrappers:
       - agl-infra-wrappers:
@@ -71,16 +72,16 @@
     builders:
       - shell: |
           set
-          #export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
+          # export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
           ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-cycle\ started.\ URL:\ ${{BUILD_URL}}" || true
-#      - multijob:
-#          name: CIB-{project}-start
-#          condition: SUCCESSFUL
-#          projects:
-#            - name: 'ci-platform-{project}-verify-CIB-start'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
+          # - multijob:
+          #     name: CIB-{project}-start
+          #     condition: SUCCESSFUL
+          #     projects:
+          #       - name: 'ci-platform-{project}-verify-CIB-start'
+          #         current-parameters: true
+          #         abort-all-job: true
+          #         kill-phase-on: FAILURE
       - multijob:
           name: CIB-{project}
           condition: SUCCESSFUL
@@ -113,14 +114,14 @@
               current-parameters: true
               abort-all-job: true
               kill-phase-on: FAILURE
-#      - multijob:
-#          name: 'CIBT-{project}-start'
-#          condition: SUCCESSFUL
-#          projects:
-#            - name: 'ci-platform-{project}-verify-CIBT-start'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
+              # - multijob:
+              #     name: 'CIBT-{project}-start'
+              #     condition: SUCCESSFUL
+              #     projects:
+              #       - name: 'ci-platform-{project}-verify-CIBT-start'
+              #         current-parameters: true
+              #         abort-all-job: true
+              #         kill-phase-on: FAILURE
       - multijob:
           name: CIBT-{project}
           condition: SUCCESSFUL
@@ -163,7 +164,7 @@
 
 #
 # -verify-failure
-####################
+# ###################
 
 - job-template:
     name: 'ci-platform-{project}-verify-failure'
@@ -211,7 +212,7 @@
 
 #
 # CIB-{machine}
-###############
+# ##############
 
 - job-template:
     name: 'ci-platform-{project}-verify-CIB-{machine}'
@@ -258,18 +259,18 @@
 
     builders:
       - shell:
-            !include-raw-escape:
-                - ../common/include-agl-header.sh
-                - ../common/include-agl-repo.sh
-                - ../common/include-agl-select.sh
-                - ../common/include-agl-source-aglsetup.sh
-                - ../common/include-agl-auto-conf.sh
-                - ../common/include-agl-limit-parallelism.sh
-                - ../common/include-agl-local-conf-fstypes.sh
-                - ../common/include-agl-cat-auto-conf.sh
-                - ../common/include-agl-bitbake-image.sh
-                - ../common/include-agl-run-test-prepare.sh
-                - ../common/include-agl-run-test-rsync-changeid.sh
+          !include-raw-escape:
+          - ../common/include-agl-header.sh
+          - ../common/include-agl-repo.sh
+          - ../common/include-agl-select.sh
+          - ../common/include-agl-source-aglsetup.sh
+          - ../common/include-agl-auto-conf.sh
+          - ../common/include-agl-limit-parallelism.sh
+          - ../common/include-agl-local-conf-fstypes.sh
+          - ../common/include-agl-cat-auto-conf.sh
+          - ../common/include-agl-bitbake-image.sh
+          - ../common/include-agl-run-test-prepare.sh
+          - ../common/include-agl-run-test-rsync-changeid.sh
     publishers:
       - naginator:
           rerun-unstable-builds: true
@@ -281,7 +282,7 @@
 
 #
 # CIB-start
-############
+# ###########
 
 - job-template:
     name: 'ci-platform-{project}-verify-CIB-start'
@@ -325,12 +326,12 @@
     builders:
       - shell: |
           set
-          #export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
-          #ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ ${{BUILD_URL}}" || true
+          # export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
+          # ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ ${{BUILD_URL}}" || true
 
 #
 # CIB-finish-success
-####################
+# ###################
 
 - job-template:
     name: 'ci-platform-{project}-verify-CIB-finish-success'
@@ -375,11 +376,9 @@
           echo "#### CIB +1 #### Verified +1 ####"
           ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified +1 --label ci-image-build=+1 -n NONE --message="CI-Image-Build\ finished,\ CIB+1,\ Verified+1" || true
 
-
-
 #
 # CIBT-{machine} 'BOOT TEST'
-############################
+# ###########################
 
 - job-template:
     name: 'ci-platform-{project}-verify-CIBT-{machine}'
@@ -431,12 +430,12 @@
 
     builders:
       - shell:
-            !include-raw-escape:
-                - ../common/include-agl-header.sh
-                - ../common/include-agl-repo.sh
-                - ../common/include-agl-select.sh
-                - ../common/include-agl-run-test-prepare.sh
-                - ../common/include-agl-run-test-short.sh
+          !include-raw-escape:
+          - ../common/include-agl-header.sh
+          - ../common/include-agl-repo.sh
+          - ../common/include-agl-select.sh
+          - ../common/include-agl-run-test-prepare.sh
+          - ../common/include-agl-run-test-short.sh
 
     publishers:
       - naginator:
@@ -449,7 +448,7 @@
 
 #
 # CIBT-start
-################
+# ###############
 
 - job-template:
     name: 'ci-platform-{project}-verify-CIBT-start'
@@ -493,13 +492,13 @@
     builders:
       - shell: |
           echo "CIBT Started"
-          #set
-          #ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --label ci-image-boot-test=0 -n NONE --message='CI-Image-Boot-Test\ started' || true
+          # set
+          # ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --label ci-image-boot-test=0 -n NONE --message='CI-Image-Boot-Test\ started' || true
 
 
 #
 # CIBT-finish-success
-#####################
+# ####################
 
 - job-template:
     name: 'ci-platform-{project}-verify-CIBT-finish-success'
@@ -542,6 +541,6 @@
 
     builders:
       - shell: |
-          #set
+          # set
           echo "#### CIBT +1 ####"
           ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified +1 --label ci-image-build=+1 --label ci-image-boot-test=+1 -n NONE --message='CI-Image-Boot-Test\ finished' || true
