Add message on failure and enhance voting
Change-Id: I5fa4f486774a1330da95007bef295f71fc691eca
Signed-off-by: Jan-Simon Möller <jsmoeller@linuxfoundation.org>

diff --git a/jjb/ci-AGL-verify/ci-platform-jjb.yaml b/jjb/ci-AGL-verify/ci-platform-jjb.yaml
--- a/jjb/ci-AGL-verify/ci-platform-jjb.yaml
+++ b/jjb/ci-AGL-verify/ci-platform-jjb.yaml
@@ -72,8 +72,9 @@
     builders:
       - shell: |
           set
-          # export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
-          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-cycle\ started.\ URL:\ ${{BUILD_URL}}" || true
+          export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
+          echo \$TRIGGERURL
+          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 -n NONE --message="CI-cycle\ started.\ URL:\ ${{BUILD_URL}}" || true
           # - multijob:
           #     name: CIB-{project}-start
           #     condition: SUCCESSFUL
@@ -155,12 +156,12 @@
               abort-all-job: true
               kill-phase-on: FAILURE
 
-    #publishers:
-    #  - trigger-parameterized-builds:
-    #    - project:
-    #      - ci-platform-{project}-verify-failure
-    #      condition: FAILED
-    #      current-parameters: true
+    publishers:
+      - trigger-parameterized-builds:
+        - project:
+          - ci-platform-{project}-verify-failure
+          condition: FAILED
+          current-parameters: true
 
 #
 # -verify-failure
@@ -207,7 +208,8 @@
       - shell: |
           set
           echo "#### Verified -1 ####"
-          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified -1 -n NONE --message="CI-cycle\ failed,\ Verified-1.\ URL:\ ${{BUILD_URL}}" || true
+          #ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified -1 -n NONE --message="CI-cycle\ failed.\ URL:\ ${{BUILD_URL}}" || true
+          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} -n NONE --message="CI-cycle\ failed.\ URL:\ ${{BUILD_URL}}" || true
 
 
 #
@@ -277,7 +279,7 @@
           progressive-delay-increment: 5
           progressive-delay-maximum: 15
           max-failed-builds: 2
-          regular-expression: "Unexpected termination of the channel"
+          #regular-expression: "Unexpected termination of the channel"
 
 
 #
@@ -325,9 +327,10 @@
 
     builders:
       - shell: |
-          set
-          # export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
+          #set
+          export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
           # ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ ${{BUILD_URL}}" || true
+          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ \$TRIGGERURL" || true
 
 #
 # CIB-finish-success
@@ -443,7 +446,7 @@
           progressive-delay-increment: 5
           progressive-delay-maximum: 15
           max-failed-builds: 2
-          regular-expression: "Unexpected termination of the channel"
+          #regular-expression: "Unexpected termination of the channel"
 
 
 #
