Build and upload app to CI folder
Change-Id: Ie7947c1a8472826a4f6ee1f4ce6ccaed56945f7c
Signed-off-by: Jan-Simon Möller <jsmoeller@linuxfoundation.org>

diff --git a/jjb/ci-apps-verify/ci-apps-jjb.yaml b/jjb/ci-apps-verify/ci-apps-jjb.yaml
--- a/jjb/ci-apps-verify/ci-apps-jjb.yaml
+++ b/jjb/ci-apps-verify/ci-apps-jjb.yaml
@@ -26,18 +26,23 @@
       - settings-wifi
     jobs:
       - ci-apps-{project}-verify
-      # - ci-apps-{project}-verify-CIB-start
       - ci-apps-{project}-verify-CIB-{architecture}
       - ci-apps-{project}-verify-CIB-finish-success
       - ci-apps-{project}-verify-failure
+
+      # - ci-apps-{project}-verify-CIB-start
       # - ci-apps-{project}-verify-CIBT-start
       #- ci-apps-{project}-verify-CIBT-{architecture}
       #- ci-apps-{project}-verify-CIBT-finish-success
 
-#
-# -verify  = trigger from gerrit and control job
-# ###############################################
 
+################################################################################################################################################################
+################################################################################################################################################################
+
+
+################################################################################
+# ci-apps-{project}-verify  =  trigger from gerrit and control job
+################################################################################
 - job-template:
     name: 'ci-apps-{project}-verify'
     project-type: multijob
@@ -64,22 +69,18 @@
           name: GERRIT_PATCHSET_NUMBER
           default: "2"
           description: "patchset # to build"
-
     build-discarder:
       days-to-keep: 30
       artifact-days-to-keep: -1
       artifact-num-to-keep: 5
-
     triggers:
       - gerrit-trigger-patch-submitted-manual-verified:
           name: 'apps/{project}'
           branch: '**/**/**'
           silent: 'true'
-
     wrappers:
       - agl-infra-wrappers:
           build-timeout: '{build-timeout}'
-
     builders:
       - shell: |
           set
@@ -100,7 +101,15 @@
           projects:
             - name: 'ci-apps-{project}-verify-CIB-arm'
               current-parameters: true
-              abort-all-job: true
+              #abort-all-job: true
+              kill-phase-on: FAILURE
+            - name: 'ci-apps-{project}-verify-CIB-aarch64'
+              current-parameters: true
+              #abort-all-job: true
+              kill-phase-on: FAILURE
+            - name: 'ci-apps-{project}-verify-CIB-x86-64'
+              current-parameters: true
+              #abort-all-job: true
               kill-phase-on: FAILURE
       - multijob:
           name: CIB-{project}-finish-success
@@ -110,163 +119,16 @@
               current-parameters: true
               abort-all-job: true
               kill-phase-on: FAILURE
-              # - multijob:
-              #     name: 'CIBT-{project}-start'
-              #     condition: SUCCESSFUL
-              #     projects:
-              #       - name: 'ci-apps-{project}-verify-CIBT-start'
-              #         current-parameters: true
-              #         abort-all-job: true
-              #         kill-phase-on: FAILURE
-      #- multijob:
-#          name: CIBT-{project}
-#          condition: SUCCESSFUL
-#          projects:
-#            - name: 'ci-apps-{project}-verify-CIBT-porter-nogfx'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
-#            - name: 'ci-apps-{project}-verify-CIBT-intel-corei7-64'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
-#            - name: 'ci-apps-{project}-verify-CIBT-raspberrypi3'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
-#            - name: 'ci-apps-{project}-verify-CIBT-dra7xx-evm'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
-#            - name: 'ci-apps-{project}-verify-CIBT-qemux86-64'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
-#      - multijob:
-#          name: 'CIBT-{project}-finish-success'
-#          condition: SUCCESSFUL
-#          projects:
-#            - name: 'ci-apps-{project}-verify-CIBT-finish-success'
-#              current-parameters: true
-#              abort-all-job: true
-#              kill-phase-on: FAILURE
-
-#    publishers:
-#      - trigger-parameterized-builds:
-#        - project:
-#          - ci-apps-{project}-verify-failure
-#          condition: FAILED
-#          current-parameters: true
-
-#
-# -verify-failure
-# ###################
-
-- job-template:
-    name: 'ci-apps-{project}-verify-failure'
-    project-type: freestyle
-    concurrent: true
-    node: control-slave
-
-    parameters:
-      - string:
-          name: GERRIT_PROJECT
-          default: 'apps/{project}'
-          description: "Project to build"
-      - string:
-          name: GERRIT_BRANCH
-          default: master
-          description: "branch to build"
-      - string:
-          name: GERRIT_REFSPEC
-          default: refs/heads/master
-          description: "refspec to build"
-      - string:
-          name: GERRIT_CHANGE_NUMBER
-          default: "8313"
-          description: "change # to build"
-      - string:
-          name: GERRIT_PATCHSET_NUMBER
-          default: "2"
-          description: "patchset # to build"
-
-    build-discarder:
-      days-to-keep: 30
-      artifact-days-to-keep: -1
-      artifact-num-to-keep: 5
-
-    wrappers:
-      - agl-infra-wrappers:
-          build-timeout: '{build-timeout}'
-
-    builders:
-      - shell: |
-          set
-          echo "#### Verified -1 ####"
-          #ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified -1 -n NONE --message="CI-cycle\ failed.\ URL:\ ${{BUILD_URL}}" || true
-          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} -n NONE --message="CI-cycle\ failed.\ URL:\ ${{BUILD_URL}}" || true
-
-#
-# CIB-start (unused)
-# ###########
-
-- job-template:
-    name: 'ci-apps-{project}-verify-CIB-start'
-    project-type: freestyle
-    concurrent: true
-    node: control-slave
-
-    parameters:
-      - string:
-          name: GERRIT_PROJECT
-          default: 'apps/{project}'
-          description: "Project to build"
-      - string:
-          name: GERRIT_BRANCH
-          default: master
-          description: "branch to build"
-      - string:
-          name: GERRIT_REFSPEC
-          default: refs/heads/master
-          description: "refspec to build"
-      - string:
-          name: GERRIT_CHANGE_NUMBER
-          default: "8313"
-          description: "change # to build"
-      - string:
-          name: GERRIT_PATCHSET_NUMBER
-          default: "2"
-          description: "patchset # to build"
-
-    build-discarder:
-      days-to-keep: 30
-      artifact-days-to-keep: -1
-      artifact-num-to-keep: 5
-
-    wrappers:
-      - agl-infra-wrappers:
-          build-timeout: '{build-timeout}'
-      - openstack:
-          single-use: false
-
-    builders:
-      - shell: |
-          #set
-          export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
-          # ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ ${{BUILD_URL}}" || true
-          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ \$TRIGGERURL" || true
 
 
-#
-# CIB-{architecture}
-# ##############
-
+################################################################################
+# ci-apps-{project}-verify-CIB-{architecture}  =  build job per arch
+################################################################################
 - job-template:
     name: 'ci-apps-{project}-verify-CIB-{architecture}'
     project-type: freestyle
     concurrent: true
     node: agl-test-slave
-
     parameters:
       - string:
           name: GERRIT_PROJECT
@@ -311,6 +173,7 @@
           - ../common/include-apps-header.sh
           - ../common/include-apps-fetch-install-sdk.sh
           - ../common/include-apps-build-app.sh
+          - ../common/include-apps-rsync-download-changeid.sh
 
     publishers:
       - naginator:
@@ -321,17 +184,14 @@
           #regular-expression: "Unexpected termination of the channel"
 
 
-
-#
-# CIB-finish-success
-# ###################
-
+################################################################################
+# ci-apps-{project}-verify-CIB-finish-succcess  =  success, msg to gerrit
+################################################################################
 - job-template:
     name: 'ci-apps-{project}-verify-CIB-finish-success'
     project-type: freestyle
     concurrent: true
     node: control-slave
-
     parameters:
       - string:
           name: GERRIT_PROJECT
@@ -353,21 +213,124 @@
           name: GERRIT_PATCHSET_NUMBER
           default: "2"
           description: "patchset # to build"
-
     build-discarder:
       days-to-keep: 30
       artifact-days-to-keep: -1
       artifact-num-to-keep: 5
-
     wrappers:
       - agl-infra-wrappers:
           build-timeout: '{build-timeout}'
-
     builders:
       - shell: |
           set
           echo "#### CIB +1 #### Verified +1 ####"
           ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified +1 --label ci-image-build=+1 -n NONE --message="CI-Image-Build\ finished,\ CIB+1,\ Verified+1" || true
+
+
+################################################################################
+# ci-apps-{project}-verify-failure  =  message back to gerrit on failure
+################################################################################
+- job-template:
+    name: 'ci-apps-{project}-verify-failure'
+    project-type: freestyle
+    concurrent: true
+    node: control-slave
+    parameters:
+      - string:
+          name: GERRIT_PROJECT
+          default: 'apps/{project}'
+          description: "Project to build"
+      - string:
+          name: GERRIT_BRANCH
+          default: master
+          description: "branch to build"
+      - string:
+          name: GERRIT_REFSPEC
+          default: refs/heads/master
+          description: "refspec to build"
+      - string:
+          name: GERRIT_CHANGE_NUMBER
+          default: "8313"
+          description: "change # to build"
+      - string:
+          name: GERRIT_PATCHSET_NUMBER
+          default: "2"
+          description: "patchset # to build"
+    build-discarder:
+      days-to-keep: 30
+      artifact-days-to-keep: -1
+      artifact-num-to-keep: 5
+    wrappers:
+      - agl-infra-wrappers:
+          build-timeout: '{build-timeout}'
+    builders:
+      - shell: |
+          set
+          echo "#### Verified -1 ####"
+          #ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified -1 -n NONE --message="CI-cycle\ failed.\ URL:\ ${{BUILD_URL}}" || true
+          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} -n NONE --message="CI-cycle\ failed.\ URL:\ ${{BUILD_URL}}" || true
+
+
+
+
+
+
+
+
+
+
+
+################################################################################################################################################################
+################################################################################################################################################################
+################################################################################################################################################################
+################################################################################################################################################################
+
+
+#
+# CIB-start (unused)
+# ###########
+- job-template:
+    name: 'ci-apps-{project}-verify-CIB-start'
+    project-type: freestyle
+    concurrent: true
+    node: control-slave
+    parameters:
+      - string:
+          name: GERRIT_PROJECT
+          default: 'apps/{project}'
+          description: "Project to build"
+      - string:
+          name: GERRIT_BRANCH
+          default: master
+          description: "branch to build"
+      - string:
+          name: GERRIT_REFSPEC
+          default: refs/heads/master
+          description: "refspec to build"
+      - string:
+          name: GERRIT_CHANGE_NUMBER
+          default: "8313"
+          description: "change # to build"
+      - string:
+          name: GERRIT_PATCHSET_NUMBER
+          default: "2"
+          description: "patchset # to build"
+    build-discarder:
+      days-to-keep: 30
+      artifact-days-to-keep: -1
+      artifact-num-to-keep: 5
+    wrappers:
+      - agl-infra-wrappers:
+          build-timeout: '{build-timeout}'
+      - openstack:
+          single-use: false
+    builders:
+      - shell: |
+          #set
+          export TRIGGERURL=$(echo ${{BUILD_URL}} | sed -e 's,-CIB-start.*,,')
+          # ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 --label ci-image-build=0 --label ci-image-boot-test=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ ${{BUILD_URL}}" || true
+          ssh -p 29418 agl-jobbuilder@gerrit.automotivelinux.org gerrit review ${{GERRIT_CHANGE_NUMBER}},${{GERRIT_PATCHSET_NUMBER}} --verified=0 -n NONE --message="CI-Image-Build\ started.\ URL:\ \$TRIGGERURL" || true
+
 
 #
 # CIBT-{architecture} 'BOOT TEST'
